### ISSUE TITLE
Missing method exception: "System.Threading.Monitor.Enter"

### ISSUE THREAD

**Issue by Seeker1437** [HearthSim/UnityHook#19]
Happens every time a hook is called.

**Comment by Bert-Proesmans** [comment]
Hi, I haven't worked with/on this project for a long time.

Does this issue happen with an out of the box configuration? Are you running a custom hook? Is there anything special about your toolchain configuration?

**Comment by Seeker1437** [comment]
Ask you ask this I think I figured out what was wrong. I built a new "HookRegistry.dll" instead of just modifying the existing one. My version is not built against the correct .NET Framework Version.  I was able to get it working after that.

**Comment by Bert-Proesmans** [comment]
If it works, great! I'm honestly a bit surprised it still works.

I'll keep this issue open for a while in case you hit another issue.

**Comment by Seeker1437** [comment]
Been playing with this more, is there a way to inject into the middle of method bodies or to replace certain calls within a method body instead of just add a hook to the beginning?

I know this can probably just be done in the hook registry code too I guess xD and not every mid-body injection can be scripted hmmmm.

This should probably be a new question issue thing haha.

**Comment by Bert-Proesmans** [comment]
Injecting in the middle of a body is certainly doable, but tough to do in batch because you need (to calculate) an opcode offset.
Replacing certain call sites is practically equivalent to hooking into the called methods.

Yes, the idea was that any complexity can be encoded into custom hook logic. This allows for the hooking code to be simpler and equivalently more robust (i wish to think).

**Comment by Seeker1437** [comment]
I have another question (I know this might be getting old lol) can I name the injected method whatever I want? I notice in your example you just call it `OnCall` it can me named differently right?

~Edit~
I  just read through the code more okay this is a little different than I was thinking, actually I can take advantage of this a little by probably reading the IL after the initial injection and detecting the required offsets after that most likely XD. I am not the most experienced but I have some previous examples to help me a bit.

**Comment by Bert-Proesmans** [comment]
With OnCall I suppose you mean the HooksRegistry class method? That's the entry point into the HookRegistry binary so if you change the name, you'll also have to change the hooking code.

I used DnSpy for IL inspection, you might find it interesting as well.

**Comment by Seeker1437** [comment]
I decided I don't have to inject in the middle of the method if I overwrite the method from the hook (by returning something other than null. I just realized that even though I read that comment a thousand times LOL
