### ISSUE TITLE
如何实现鼠标hook呢，看了下源码，还是不太会呀，求大佬帮助

### ISSUE THREAD

**Issue by hahaCrazy** [HearthSim/UnityHook#20]

**Comment by Bert-Proesmans** [comment]
Hi! A mouse hook is a very generic term. Do you want to hook click events, or mouse move events, or scroll events?

To hook a mouse click event, follow this high-level procedure. The details are game-specific and up to you to fill in.

1. Find the full pathname of the class + method of the mouse click handler you want to hook
2. Write down that path in the file /hooker/example_hooks
3. Make a file copy of /HookRegistry/srs/hooks/HookTemplate.cs
4. Fill in hook logic, see the contents of other hook files for ideas
5. Compile project HookRegistry into dll file
6. Update project GameKnowledgeBase with file path details of your game
6. Adapt and run project Hooker, providing the game installation path, location of example_hooks, location of HookRegistry dll
     1. see https://github.com/HearthSim/UnityHook#usage-example for details
